
/* Drop Tables */

DROP TABLE SEAT CASCADE CONSTRAINTS;
DROP TABLE HALL CASCADE CONSTRAINTS;
DROP TABLE THEATER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE HALL
(
	HALL_NO number(10,0) NOT NULL,
	HALL_NAME varchar2(255),
	HALL_SEAT_NO number(10,0),
	SPECIAL_HALL_EXIST varchar2(10) CONSTRAINT SPECIAL_HALL_EXIST_CK CHECK SPECIAL_HALL_EXIST IN ('Y', 'N'),
	SPECIAL_PRICE number(10,0),
	THEATER_NO number(10,0) NOT NULL,
	PRIMARY KEY (HALL_NO)
);


CREATE TABLE SEAT
(
	SEAT_NO number(10,0) NOT NULL,
	SEAT_ROW varchar2(10),
	SEAT_NAME varchar2(10),
	HALL_NO number(10,0) NOT NULL,
	PRIMARY KEY (SEAT_NO)
);


CREATE TABLE THEATER
(
	THEATER_NO number(10,0) NOT NULL,
	THEATER_NAME varchar2(255),
	THEATER_LOACTION varchar2(255),
	THEATER_ADDRESS varchar2(255),
	THEATER_FACILITY varchar2(255),
	SPECIAL_HALL_EXIST varchar2(10) CONSTRAINT SPECIAL_HALL_EXIST_CK CHECK SPECIAL_HALL_EXIST IN ('Y', 'N'),
	THEATER_LATITUDE number(10,0),
	THEATER_LONGITUDE number(10,0),
	PRIMARY KEY (THEATER_NO)
);



/* Create Foreign Keys */

ALTER TABLE SEAT
	ADD FOREIGN KEY (HALL_NO)
	REFERENCES HALL (HALL_NO)
;


ALTER TABLE HALL
	ADD FOREIGN KEY (THEATER_NO)
	REFERENCES THEATER (THEATER_NO)
;



